/**
 * 日期时间工具库。基于 {@link https://date-fns.org/v2.14.0/docs/Getting-Started | date-fns}。
 *
 * @packageDocumentation
 */

/* istanbul ignore file */

// prettier-ignore
export {
  // 手动导出以解决 @microsoft/api-extractor 的问题
  // @index(['../../node_modules/date-fns/esm/*', '!**/{_*,locale,constants,fp}'], (f, _) => `${f.name.replace(/-/g, '')},`, { onlyDirectories: true })
  add,
  addBusinessDays,
  addDays,
  addHours,
  addISOWeekYears,
  addMilliseconds,
  addMinutes,
  addMonths,
  addQuarters,
  addSeconds,
  addWeeks,
  addYears,
  areIntervalsOverlapping,
  clamp,
  closestIndexTo,
  closestTo,
  compareAsc,
  compareDesc,
  daysToWeeks,
  differenceInBusinessDays,
  differenceInCalendarDays,
  differenceInCalendarISOWeeks,
  differenceInCalendarISOWeekYears,
  differenceInCalendarMonths,
  differenceInCalendarQuarters,
  differenceInCalendarWeeks,
  differenceInCalendarYears,
  differenceInDays,
  differenceInHours,
  differenceInISOWeekYears,
  differenceInMilliseconds,
  differenceInMinutes,
  differenceInMonths,
  differenceInQuarters,
  differenceInSeconds,
  differenceInWeeks,
  differenceInYears,
  eachDayOfInterval,
  eachHourOfInterval,
  eachMinuteOfInterval,
  eachMonthOfInterval,
  eachQuarterOfInterval,
  eachWeekendOfInterval,
  eachWeekendOfMonth,
  eachWeekendOfYear,
  eachWeekOfInterval,
  eachYearOfInterval,
  endOfDay,
  endOfDecade,
  endOfHour,
  endOfISOWeek,
  endOfISOWeekYear,
  endOfMinute,
  endOfMonth,
  endOfQuarter,
  endOfSecond,
  endOfToday,
  endOfTomorrow,
  endOfWeek,
  endOfYear,
  endOfYesterday,
  format,
  formatDistance,
  formatDistanceStrict,
  formatDistanceToNow,
  formatDistanceToNowStrict,
  formatDuration,
  formatISO,
  formatISO9075,
  formatISODuration,
  formatRelative,
  formatRFC3339,
  formatRFC7231,
  fromUnixTime,
  getDate,
  getDay,
  getDayOfYear,
  getDaysInMonth,
  getDaysInYear,
  getDecade,
  getHours,
  getISODay,
  getISOWeek,
  getISOWeeksInYear,
  getISOWeekYear,
  getMilliseconds,
  getMinutes,
  getMonth,
  getOverlappingDaysInIntervals,
  getQuarter,
  getSeconds,
  getTime,
  getUnixTime,
  getWeek,
  getWeekOfMonth,
  getWeeksInMonth,
  getWeekYear,
  getYear,
  hoursToMilliseconds,
  hoursToMinutes,
  hoursToSeconds,
  intervalToDuration,
  intlFormat,
  isAfter,
  isBefore,
  isDate,
  isEqual,
  isExists,
  isFirstDayOfMonth,
  isFriday,
  isFuture,
  isLastDayOfMonth,
  isLeapYear,
  isMatch,
  isMonday,
  isPast,
  isSameDay,
  isSameHour,
  isSameISOWeek,
  isSameISOWeekYear,
  isSameMinute,
  isSameMonth,
  isSameQuarter,
  isSameSecond,
  isSameWeek,
  isSameYear,
  isSaturday,
  isSunday,
  isThisHour,
  isThisISOWeek,
  isThisMinute,
  isThisMonth,
  isThisQuarter,
  isThisSecond,
  isThisWeek,
  isThisYear,
  isThursday,
  isToday,
  isTomorrow,
  isTuesday,
  isValid,
  isWednesday,
  isWeekend,
  isWithinInterval,
  isYesterday,
  lastDayOfDecade,
  lastDayOfISOWeek,
  lastDayOfISOWeekYear,
  lastDayOfMonth,
  lastDayOfQuarter,
  lastDayOfWeek,
  lastDayOfYear,
  lightFormat,
  max,
  milliseconds,
  millisecondsToHours,
  millisecondsToMinutes,
  millisecondsToSeconds,
  min,
  minutesToHours,
  minutesToMilliseconds,
  minutesToSeconds,
  monthsToQuarters,
  monthsToYears,
  nextDay,
  nextFriday,
  nextMonday,
  nextSaturday,
  nextSunday,
  nextThursday,
  nextTuesday,
  nextWednesday,
  parse,
  parseISO,
  parseJSON,
  previousDay,
  previousFriday,
  previousMonday,
  previousSaturday,
  previousSunday,
  previousThursday,
  previousTuesday,
  previousWednesday,
  quartersToMonths,
  quartersToYears,
  roundToNearestMinutes,
  secondsToHours,
  secondsToMilliseconds,
  secondsToMinutes,
  set,
  setDate,
  setDay,
  setDayOfYear,
  setHours,
  setISODay,
  setISOWeek,
  setISOWeekYear,
  setMilliseconds,
  setMinutes,
  setMonth,
  setQuarter,
  setSeconds,
  setWeek,
  setWeekYear,
  setYear,
  startOfDay,
  startOfDecade,
  startOfHour,
  startOfISOWeek,
  startOfISOWeekYear,
  startOfMinute,
  startOfMonth,
  startOfQuarter,
  startOfSecond,
  startOfToday,
  startOfTomorrow,
  startOfWeek,
  startOfWeekYear,
  startOfYear,
  startOfYesterday,
  sub,
  subBusinessDays,
  subDays,
  subHours,
  subISOWeekYears,
  subMilliseconds,
  subMinutes,
  subMonths,
  subQuarters,
  subSeconds,
  subWeeks,
  subYears,
  toDate,
  weeksToDays,
  yearsToMonths,
  yearsToQuarters,
  // @endindex
} from 'date-fns/esm'

// prettier-ignore
export {
  // 手动导出以解决 @microsoft/api-extractor 的问题
  // ref: https://github.com/date-fns/date-fns/blob/master/scripts/_lib/listLocales.js#L13
  // ref: https://github.com/date-fns/date-fns/blob/master/outdatedLocales.json
  // @index(['../../node_modules/date-fns/esm/locale/*', '!**/{_*,ar,fil,fr-CH,nl-BE}'], (f, _) => `${f.name.replace(/-/g, '')} as ${f.name.replace(/-/g, '')}Locale,`, { onlyDirectories: true })
  af as afLocale,
  arDZ as arDZLocale,
  arMA as arMALocale,
  arSA as arSALocale,
  arTN as arTNLocale,
  az as azLocale,
  be as beLocale,
  bg as bgLocale,
  bn as bnLocale,
  bs as bsLocale,
  ca as caLocale,
  cs as csLocale,
  cy as cyLocale,
  da as daLocale,
  de as deLocale,
  deAT as deATLocale,
  el as elLocale,
  enAU as enAULocale,
  enCA as enCALocale,
  enGB as enGBLocale,
  enIN as enINLocale,
  enNZ as enNZLocale,
  enUS as enUSLocale,
  enZA as enZALocale,
  eo as eoLocale,
  es as esLocale,
  et as etLocale,
  eu as euLocale,
  faIR as faIRLocale,
  fi as fiLocale,
  fr as frLocale,
  frCA as frCALocale,
  gd as gdLocale,
  gl as glLocale,
  gu as guLocale,
  he as heLocale,
  hi as hiLocale,
  hr as hrLocale,
  ht as htLocale,
  hu as huLocale,
  hy as hyLocale,
  id as idLocale,
  is as isLocale,
  it as itLocale,
  ja as jaLocale,
  ka as kaLocale,
  kk as kkLocale,
  kn as knLocale,
  ko as koLocale,
  lb as lbLocale,
  lt as ltLocale,
  lv as lvLocale,
  mk as mkLocale,
  mn as mnLocale,
  ms as msLocale,
  mt as mtLocale,
  nb as nbLocale,
  nl as nlLocale,
  nn as nnLocale,
  pl as plLocale,
  pt as ptLocale,
  ptBR as ptBRLocale,
  ro as roLocale,
  ru as ruLocale,
  sk as skLocale,
  sl as slLocale,
  sq as sqLocale,
  sr as srLocale,
  srLatn as srLatnLocale,
  sv as svLocale,
  ta as taLocale,
  te as teLocale,
  th as thLocale,
  tr as trLocale,
  ug as ugLocale,
  uk as ukLocale,
  uz as uzLocale,
  vi as viLocale,
  zhCN as zhCNLocale,
  zhTW as zhTWLocale,
  // @endindex
} from 'date-fns/esm/locale'

// @index(['./**/*.ts', '!./**/*.test.*'], f => `export * from '${f.path}'`)
export * from './anyToDate'
export * from './formatDate'
export * from './formatDistanceAgo'
export * from './intervalToRestrictiveDuration'
export * from './ms'
export * from './numeralDayToChineseDay'
// @endindex
